name: Publish to PyPI

on:
  release:
    types: [created]
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Update dependencies for non-macOS
        run: |
          # Remove mlx dependency for non-macOS systems
          sed -i '/mlx =/d' pyproject.toml
          sed -i '/mlx-lm =/d' pyproject.toml
          # Update lock file
          poetry lock --no-update

      - name: Install dependencies
        run: |
          poetry install --without dev

      - name: Build package
        run: |
          poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          # Remove the following line if you've already uploaded to PyPI
          skip_existing: true
